# Generated by Django 2.1.4 on 2019-02-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police',
            fields=[
                ('police_id', models.IntegerField(primary_key=True, serialize=False)),
                ('police_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField(max_length=15)),
                ('designation', models.CharField(max_length=15)),
                ('station_id', models.IntegerField(max_length=5)),
            ],
        ),
    ]
