# Generated by Django 2.1.4 on 2019-02-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190220_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detective',
            fields=[
                ('detective_id', models.IntegerField(primary_key=True, serialize=False)),
                ('detective_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('mobile_no', models.IntegerField(max_length=15)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
