# Generated by Django 2.1.4 on 2019-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detective',
            name='mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='police',
            name='mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='police',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='police',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
