# Generated by Django 2.1.4 on 2019-02-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190221_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
