# Generated by Django 2.1.4 on 2019-02-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190221_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='date_of_birth',
            field=models.DateField(default=False),
        ),
    ]
