# Generated by Django 2.1.4 on 2019-02-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complent',
            fields=[
                ('complent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('complent_type', models.CharField(max_length=20)),
                ('complient_name', models.CharField(max_length=30)),
                ('date_of_complent', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('proof', models.FileField(upload_to='Doucuments/proof')),
                ('location', models.CharField(max_length=50)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Station')),
            ],
        ),
    ]
