# Generated by Django 2.1.4 on 2019-02-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190225_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('criminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('criminal_name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='document/criminal/Image')),
                ('crime', models.CharField(max_length=100)),
            ],
        ),
    ]
